{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "SalesOrderItems",
        "Service": "/DanielMDKDemo/Services/com_sap_edm_sampleservice_v4.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "CurrencyCode": "#Page:SalesOrderItems_Edit/#Control:CurrencyCode/#Value",
        "DeliveryDate": "#Page:SalesOrderItems_Edit/#Control:DeliveryDate/#Value",
        "GrossAmount": "#Page:SalesOrderItems_Edit/#Control:GrossAmount/#Value",
        "ItemNumber": "#Page:SalesOrderItems_Edit/#Control:ItemNumber/#Value",
        "NetAmount": "#Page:SalesOrderItems_Edit/#Control:NetAmount/#Value",
        "ProductID": "#Page:SalesOrderItems_Edit/#Control:ProductID/#SelectedValue",
        "Quantity": "#Page:SalesOrderItems_Edit/#Control:Quantity/#Value",
        "QuantityUnit": "#Page:SalesOrderItems_Edit/#Control:QuantityUnit/#Value",
        "SalesOrderID": "#Page:SalesOrderItems_Edit/#Control:SalesOrderID/#SelectedValue",
        "TaxAmount": "#Page:SalesOrderItems_Edit/#Control:TaxAmount/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/DanielMDKDemo/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/DanielMDKDemo/Actions/UpdateEntityFailureMessage.action"
}